name: Changelog check

on:
  pull_request:
    # We will not track changes for the following packages/directories.
    paths-ignore:
      - "/examples/"
    # Run on labeled/unlabeled in addition to defaults to detect
    # adding/removing skip-changelog labels.
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Check that changelog updated
        uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: "skip-changelog"
          missingUpdateErrorMessage: "Please add a changelog entry in the CHANGELOG.md file."